### first stage
FROM node:14-slim AS builder

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

## second stage
FROM caddy:2.1.1-alpine

ARG CADDYFILE 
COPY ${CADDYFILE} /etc/caddy/Caddyfile 

COPY --from=builder /usr/src/app/build /srv

EXPOSE 80

EXPOSE 443
