version: "3"
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    build: ./server/
    stdin_open: true
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-app
    ports:
      - "5001:5001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    stdin_open: true
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local

